### ISSUE TITLE
void-return issue

### ISSUE THREAD

**Issue by CatsMiaow** [microsoft/dtslint#110]
vscode: 1.20.1
typescript: 2.7.2
tslint: 5.9.1
dtslint: 0.2.0

```json
{
  "extends": "dtslint/dtslint.json",
  "rules": {}
}
```

[void-return.md](/Microsoft/dtslint/blob/master/docs/void-return.md) Good: example test error
![image](https://user-images.githubusercontent.com/1300172/36472101-1055748c-1734-11e8-9403-68fde1b824dc.png)

**Comment by pe8ter** [comment]
It looks like when TypeScript builds the AST for a _d.ts_ that contains

```TypeScript
export function a(): void;
```

the `SyntaxKind` of the parent node of the `void` keyword is `VariableDeclarationList`. By adding this `SyntaxKind` to `mayContainVoid()`'s switch statement in _voidReturnRule.ts_, dtslint correctly identifies this export as an allowable `void`.

I'm not certain if the TypeScript AST builder's use `VariableDeclarationList` as the `SyntaxKind` here is the bug, or if dtslint's omission of the `SyntaxKind` is the bug. If the AST builder is doing the correct thing, then that makes this case hard to test, since tslint seems to assume that all the _.ts.lint_ test data files are for testing _.ts_ code and not _d.ts_ code.

**Comment by thw0rted** [comment]
I'm seeing something vaguely similar but don't know enough TS AST internals to tell if it's the same issue or a different one.  I'm linting

export namespace reconnect {
  interface Instance {
    reset(): void;
  }
}

The linter flags the member function with violating `void-return`, which is obviously wrong, but the thing that really drives me crazy is if I change it to `class Instance` (instead of `interface`) it works fine.

**Comment by andy-ms** [comment]
@thw0rted I don't see any error when pasting that code into `DefinitelyTyped/types/abs` and running `npm run lint abs`. Maybe your install is corrupted?

**Comment by thw0rted** [comment]
Per my comment in #115, cleaning my node_modules / package-lock did resolve the problem.

**Comment by Maxim-Mazurok** [comment]
I had same issue when updating from 3.6.2 to 3.6.4.
Always remember to update both dtslint and typescript, using `npm install typescript@next` as it is in dtslint package.lock.
