### ISSUE TITLE
definitelytyped-header-parser - publish as an NPM package

### ISSUE THREAD

**Issue by DavieReid** [Microsoft/dtslint#140]
I would like to use `dtslint` in my project but due to company policy all npm dependencies must be pulled into an internal npm.

I can't add `dtslint` into the internal npm due to the `definitelytyped-header-parser` dependency which is pulled directly from a repo in github.

Are you willing to publish `definitelytyped-header-parser` to npm and update `dtslint` to reference that new npm package rather than the current config?

**Comment by nolakara** [comment]
I ran in to this as well. We have a tool which builds definitions out of our jsdoc doclets. We wanted to make sure that we are always dtslint compliant with the new APIs we add in each version. I tried adding dtslint in to our project and ran in to the same problem as it is pulling dependancies directly from github. Is there a plan to move all the dependancies to npm so that we can have dtslint running with our build and not have a surprise when we finally try to push our new set of APIs to definitely typed?

**Comment by Rokt33r** [comment]
Please do this.... We need a protection when there are breaking changes in `definitelytyped-header-parser `. For now, I'm thinking I should fork the repo and publish as scoped package..

**Comment by buschtoens** [comment]
This has caused me trouble here: https://github.com/Microsoft/dtslint/issues/166

**Comment by sandersn** [comment]
New maintainer here! This is probably the next thing I will try.

Unless there is some surprising advantage of installing from github's production branch, I think it should be simple.

**Comment by sandersn** [comment]
OK, definitelytyped-header-parser is now on NPM at version 1.0.0.

I'll switch dtslint over to the npm version next.

**Comment by sandersn** [comment]
Except, haha, I forgot to set up a main in definitelytyped-header-parser. 1.0.1 is up now. Maybe it works?

**Comment by sandersn** [comment]
* dtslint
* dts-critic
* types-publisher
are now all updated to use the npm version of definitelytyped-header-parser.

I'm working on switching types-publisher to the npm version of dtslint as well, at which point I'll stop using the production branch here.

**Comment by DavieReid** [comment]
@sandersn Thanks a lot for taking the time to do this. I will try this out on Monday!
